/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./api/context/index"
import type { core, connectionPluginCore } from "nexus"
declare global {
  interface NexusGenCustomInputMethods<TypeName extends string> {
    /**
     * Must and only use for input
     */
    relayId<FieldName extends string>(fieldName: FieldName, opts?: core.CommonInputFieldConfig<TypeName, FieldName>): void // "RelayId";
  }
}
declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Must and only use for input
     */
    relayId<FieldName extends string>(fieldName: FieldName, ...opts: core.ScalarOutSpread<TypeName, FieldName>): void // "RelayId";
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void
  }
}


declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  MessageSendInput: { // input type
    content: string; // String!
    roomId: NexusGenScalars['RelayId']; // RelayId!
  }
  MessageSentInput: { // input type
    roomId: NexusGenScalars['RelayId']; // RelayId!
  }
  OthersConnectionWhere: { // input type
    name?: string | null; // String
  }
  RoomAddUserInput: { // input type
    participantId: NexusGenScalars['RelayId']; // RelayId!
    roomId: NexusGenScalars['RelayId']; // RelayId!
  }
  RoomCreateInput: { // input type
    name?: string | null; // String
    participantIds: NexusGenScalars['RelayId'][]; // [RelayId!]!
  }
  UserLoginInput: { // input type
    email: string; // String!
    password: string; // String!
  }
  UserRoomConnectionWhere: { // input type
    name?: string | null; // String
  }
  UserSignupInput: { // input type
    avatar?: string | null; // String
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
    password: string; // String!
  }
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
  RelayId: any
}

export interface NexusGenObjects {
  Message: { // root type
    content: string; // String!
  }
  MessageConnection: { // root type
    edges?: Array<NexusGenRootTypes['MessageEdge'] | null> | null; // [MessageEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  MessageEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['Message'] | null; // Message
  }
  MessageSendPayload: { // root type
    message?: NexusGenRootTypes['Message'] | null; // Message
  }
  MessageSentPayload: { // root type
    message?: NexusGenRootTypes['Message'] | null; // Message
  }
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Query: {};
  Room: {};
  RoomAddUserPayload: { // root type
    participant?: NexusGenRootTypes['User'] | null; // User
  }
  RoomConnection: { // root type
    edges?: Array<NexusGenRootTypes['RoomEdge'] | null> | null; // [RoomEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  RoomCreatePayload: { // root type
    room?: NexusGenRootTypes['Room'] | null; // Room
  }
  RoomEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['Room'] | null; // Room
  }
  Subscription: {};
  User: { // root type
    avatar?: string | null; // String
    email: string; // String!
    firstName: string; // String!
    lastName: string; // String!
  }
  UserConnection: { // root type
    edges?: Array<NexusGenRootTypes['UserEdge'] | null> | null; // [UserEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  UserEdge: { // root type
    cursor: string; // String!
    node?: NexusGenRootTypes['User'] | null; // User
  }
  UserLoginPayload: { // root type
    jwt: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  UserSignupPayload: { // root type
    jwt: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
}

export interface NexusGenInterfaces {
  Node: NexusGenRootTypes['Message'] | NexusGenRootTypes['Room'] | NexusGenRootTypes['User'];
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenInterfaces & NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  Message: { // field return type
    author: NexusGenRootTypes['User']; // User!
    content: string; // String!
    id: string; // ID!
  }
  MessageConnection: { // field return type
    edges: Array<NexusGenRootTypes['MessageEdge'] | null> | null; // [MessageEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  MessageEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Message'] | null; // Message
  }
  MessageSendPayload: { // field return type
    message: NexusGenRootTypes['Message'] | null; // Message
  }
  MessageSentPayload: { // field return type
    message: NexusGenRootTypes['Message'] | null; // Message
  }
  Mutation: { // field return type
    login: NexusGenRootTypes['UserLoginPayload']; // UserLoginPayload!
    messageSend: NexusGenRootTypes['MessageSendPayload'] | null; // MessageSendPayload
    roomAddUser: NexusGenRootTypes['RoomAddUserPayload'] | null; // RoomAddUserPayload
    roomCreate: NexusGenRootTypes['RoomCreatePayload'] | null; // RoomCreatePayload
    signup: NexusGenRootTypes['UserSignupPayload']; // UserSignupPayload!
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Query: { // field return type
    me: NexusGenRootTypes['User'] | null; // User
    node: NexusGenRootTypes['Node'] | null; // Node
  }
  Room: { // field return type
    host: NexusGenRootTypes['User']; // User!
    id: string; // ID!
    messages: NexusGenRootTypes['MessageConnection']; // MessageConnection!
    name: string | null; // String
    participants: NexusGenRootTypes['User'][]; // [User!]!
  }
  RoomAddUserPayload: { // field return type
    participant: NexusGenRootTypes['User'] | null; // User
  }
  RoomConnection: { // field return type
    edges: Array<NexusGenRootTypes['RoomEdge'] | null> | null; // [RoomEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  RoomCreatePayload: { // field return type
    room: NexusGenRootTypes['Room'] | null; // Room
  }
  RoomEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['Room'] | null; // Room
  }
  Subscription: { // field return type
    messageSent: NexusGenRootTypes['MessageSentPayload'] | null; // MessageSentPayload
  }
  User: { // field return type
    avatar: string | null; // String
    email: string; // String!
    firstName: string; // String!
    id: string; // ID!
    lastName: string; // String!
    name: string; // String!
    others: NexusGenRootTypes['UserConnection']; // UserConnection!
    rooms: NexusGenRootTypes['RoomConnection']; // RoomConnection!
  }
  UserConnection: { // field return type
    edges: Array<NexusGenRootTypes['UserEdge'] | null> | null; // [UserEdge]
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  UserEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['User'] | null; // User
  }
  UserLoginPayload: { // field return type
    jwt: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  UserSignupPayload: { // field return type
    jwt: string; // String!
    user: NexusGenRootTypes['User']; // User!
  }
  Node: { // field return type
    id: string; // ID!
  }
}

export interface NexusGenFieldTypeNames {
  Message: { // field return type name
    author: 'User'
    content: 'String'
    id: 'ID'
  }
  MessageConnection: { // field return type name
    edges: 'MessageEdge'
    pageInfo: 'PageInfo'
  }
  MessageEdge: { // field return type name
    cursor: 'String'
    node: 'Message'
  }
  MessageSendPayload: { // field return type name
    message: 'Message'
  }
  MessageSentPayload: { // field return type name
    message: 'Message'
  }
  Mutation: { // field return type name
    login: 'UserLoginPayload'
    messageSend: 'MessageSendPayload'
    roomAddUser: 'RoomAddUserPayload'
    roomCreate: 'RoomCreatePayload'
    signup: 'UserSignupPayload'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Query: { // field return type name
    me: 'User'
    node: 'Node'
  }
  Room: { // field return type name
    host: 'User'
    id: 'ID'
    messages: 'MessageConnection'
    name: 'String'
    participants: 'User'
  }
  RoomAddUserPayload: { // field return type name
    participant: 'User'
  }
  RoomConnection: { // field return type name
    edges: 'RoomEdge'
    pageInfo: 'PageInfo'
  }
  RoomCreatePayload: { // field return type name
    room: 'Room'
  }
  RoomEdge: { // field return type name
    cursor: 'String'
    node: 'Room'
  }
  Subscription: { // field return type name
    messageSent: 'MessageSentPayload'
  }
  User: { // field return type name
    avatar: 'String'
    email: 'String'
    firstName: 'String'
    id: 'ID'
    lastName: 'String'
    name: 'String'
    others: 'UserConnection'
    rooms: 'RoomConnection'
  }
  UserConnection: { // field return type name
    edges: 'UserEdge'
    pageInfo: 'PageInfo'
  }
  UserEdge: { // field return type name
    cursor: 'String'
    node: 'User'
  }
  UserLoginPayload: { // field return type name
    jwt: 'String'
    user: 'User'
  }
  UserSignupPayload: { // field return type name
    jwt: 'String'
    user: 'User'
  }
  Node: { // field return type name
    id: 'ID'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    login: { // args
      input: NexusGenInputs['UserLoginInput']; // UserLoginInput!
    }
    messageSend: { // args
      input: NexusGenInputs['MessageSendInput']; // MessageSendInput!
    }
    roomAddUser: { // args
      input: NexusGenInputs['RoomAddUserInput']; // RoomAddUserInput!
    }
    roomCreate: { // args
      input: NexusGenInputs['RoomCreateInput']; // RoomCreateInput!
    }
    signup: { // args
      input: NexusGenInputs['UserSignupInput']; // UserSignupInput!
    }
  }
  Query: {
    node: { // args
      id: string; // ID!
    }
  }
  Room: {
    messages: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Subscription: {
    messageSent: { // args
      input: NexusGenInputs['MessageSentInput']; // MessageSentInput!
    }
  }
  User: {
    others: { // args
      after?: string | null; // String
      first: number; // Int!
      where?: NexusGenInputs['OthersConnectionWhere'] | null; // OthersConnectionWhere
    }
    rooms: { // args
      after?: string | null; // String
      first: number; // Int!
      where?: NexusGenInputs['UserRoomConnectionWhere'] | null; // UserRoomConnectionWhere
    }
  }
}

export interface NexusGenAbstractTypeMembers {
  Node: "Message" | "Room" | "User"
}

export interface NexusGenTypeInterfaces {
  Message: "Node"
  Room: "Node"
  User: "Node"
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = keyof NexusGenInterfaces;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = "Node";

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}